//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ServicoWCF;
using System.Collections.Generic;
using System.Linq;

namespace Dados
{
    public class Dados
    {
        public bool Inserir(empresa empresa)
        {
            empresaEntities context = new empresaEntities();
            context.empresa.Add(empresa);
            int retorno = context.SaveChanges();

            return retorno == 1;
        }

        public List<empresa> Listar()
        {
            var context = new empresaEntities();
            return context.empresa.ToList();
        }

    }
}