//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public Nullable<int> QtdFuncionario { get; set; }
        public string Endereco { get; set; }
    }
}
